# Site settings
title: Yêu Ngôn
url: "http://vuongnguyen.net"
baseurl: "" # the prefix of your site uri, eg. `/jekyll-theme-EasyBook` or just one slash `/`
timezone: Auckland
description: >
   | Lynda on the go.

# Your information
email: 
author: Vuong Nguyen
avatar: ""
profile: Lynda guy.
twitter_username: 
github_username:  yeungon

# Comment Service
#  choose one and un-comment the line to active it
disqus_shortname: 

permalink: /:year/:month/:title.html
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 10
paginate_path: "page/:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
